x-common-env: &common-env
  DATABASE_URI: postgresql+asyncpg://${DATABASE_USER:-museflow}:${DATABASE_PASSWORD:-museflow}@db:${DATABASE_PORT:-5432}/${DATABASE_PATH:-museflow}

services:
  db:
    image: postgres:17.8
    container_name: museflow-db
    environment:
      POSTGRES_USER: ${DATABASE_USER:-museflow}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-museflow}
      POSTGRES_DB: ${DATABASE_PATH:-museflow}
    ports:
      - ${DATABASE_PORT:-5432}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-museflow} -d ${DATABASE_PATH:-museflow}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - museflow-network

  migration:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.13}
        UV_VERSION: ${UV_VERSION:-0.10.8}
    container_name: museflow-migration
    command: alembic upgrade head
    environment:
      <<: *common-env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - museflow-network
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.13}
        UV_VERSION: ${UV_VERSION:-0.10.8}
    container_name: museflow-app
    environment:
      <<: *common-env
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID:-dummy-client-id}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET:-dummy-client-secret}
      MUSEFLOW_SECRET_KEY: ${MUSEFLOW_SECRET_KEY:-dummy-app-secret-key-wUthyXrnRohATQkaVqIL8RRfdSoSuKQf}
    ports:
      - ${APP_PORT_LOCAL_FORWARD:-8000}:8000
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    networks:
      - museflow-network
    restart: unless-stopped

  wiremock-spotify:
    image: wiremock/wiremock:3.12.0
    container_name: museflow-wiremock-spotify
    ports:
      - "8081:8080"
      - "8444:8443"
    volumes:
      - ./tests/assets/wiremock/spotify:/home/wiremock
    command: ["--verbose", "--https-port", "8443", "--global-response-templating"]

volumes:
  db_data:

networks:
  museflow-network:
    driver: bridge
